version: '3.1'
services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DBNAME}
      PGDATA: /pg-data
    ports:
      - "5433:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  redis:
    image: "redis:alpine"
    command: redis-server
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
    container_name: my-city-api-redis
  backend:
    build: .
    image: kirigaikabuto/my-city-api
    depends_on:
      - redis
      - database
    ports:
      - ${PORT}:${PORT}
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DBNAME}
      POSTGRES_PARAM: ${POSTGRES_PARAM}
      POSTGRES_USER: ${POSTGRES_USER}
      PORT: ${PORT}
    container_name: my-city-api
  proxy:
    build: proxy
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      PORT: ${PORT}
  front:
      build: clear-city
      ports:
        - "8080:8080"
      depends_on:
        - proxy
volumes:
  database_data:
    driver: local