version: '3.1'
services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DBNAME}
      PGDATA: /pg-data
    ports:
      - "5433:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  redis:
    image: "redis:alpine"
    command: redis-server
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
    container_name: my-city-api-redis
  backend:
    build: .
    image: kirigaikabuto/my-city-api
    depends_on:
      - redis
      - database
      - backend-django
    ports:
      - ${PORT}:${PORT}
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DBNAME}
      POSTGRES_PARAM: ${POSTGRES_PARAM}
      POSTGRES_USER: ${POSTGRES_USER}
      PORT: ${PORT}
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_BUCKET: ${S3_BUCKET}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_FILE_UPLOAD_PATH: ${S3_FILE_UPLOAD_PATH}
      S3_REGION: ${S3_REGION}
      TWILIO_SID: ${TWILIO_SID}
      TWILIO_TOKEN: ${TWILIO_TOKEN}
      TWILIO_NUMBER: ${TWILIO_NUMBER}
    container_name: my-city-api
  backend-django:
    depends_on:
      - redis
      - database
    build: ../clear-city-django-api
    command: >
      sh -c "python manage.py migrate &&
             python manage.py create_admin &&
             python manage.py runserver 0.0.0.0:$DJANGO_PORT"

    volumes:
      - ../clear-city-django-api/:/usr/src/app/
    ports:
      - ${DJANGO_PORT}:${DJANGO_PORT}
    environment:
      DJANGO_PORT: ${DJANGO_PORT}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DBNAME}
      POSTGRES_PARAM: ${POSTGRES_PARAM}
      POSTGRES_USER: ${POSTGRES_USER}
    container_name: backend-django-api
  proxy:
    build: proxy
    ports:
      - "80:80"
    depends_on:
      - front
    environment:
      PORT: ${PORT}
  front:
    build: ../clear-city
    ports:
      - "8080:8080"
    depends_on:
      - backend
volumes:
  database_data:
    driver: local